// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using iotdustbin.Data;

namespace iotdustbin.Migrations
{
    [DbContext(typeof(iotdustbinDbContext))]
    [Migration("20220518074731_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("iotdustbin.Models.veriler", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("atesdurumu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("buzzer")
                        .HasColumnType("int");

                    b.Property<float>("doluluk")
                        .HasColumnType("real");

                    b.Property<int>("fan")
                        .HasColumnType("int");

                    b.Property<string>("gazdurumu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("kapakacma")
                        .HasColumnType("int");

                    b.Property<float>("sicaklik")
                        .HasColumnType("real");

                    b.HasKey("id");

                    b.ToTable("verilers");
                });
#pragma warning restore 612, 618
        }
    }
}
